# -*- coding: utf-8 -*-
"""Trabalho Estrutura de Dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ptFeSj2nVtJMHBLY_tZEmwnC4mUddsAJ
"""

#TRABALHO ESTRUTURA DE DADOS
#INTEGRANTES: SAMUEL PAES - 04099977, MATHEUS BARBOSA ALMEIDA - 04096374, Robert de Lima Aracati - 04095398

import time
import random

codigo = ""
nome = ""
preco = 0
quantidade = 0
estoque = {"0001":["Camisa básica", 30.00, 50], "0002":["Bermuda Jeans", 60.00, 30],
           "0003":["Calça Jeans", 70.00, 30],"0004":["Blusa Moletom", 100.00, 10],"0005":["Camisa Social", 160.00, 2],"0006":["Calça Social", 230.00, 3],
           "0007":["Boné", 15.00, 10], "0008":["Sapato Social", 600.00, 1], "0009":["Tênis Sport", 130.00, 5], "0010":["Cueca Box", 15.00, 4]}
opcao = 0
loop = 1
refazer = 1

#LOOP PARA MANTER O PROGRAMA RODANDO ATÉ QUE O USUÁRIO ESCOLHA ENCERRAR.
while loop ==1:

  #SE O ESTOQUE NÃO HOUVER ITENS, FORÇAR INSERIR PRODUTOS NO ESTOQUE
  if len(estoque.keys()) <=0:

    print("\n\n>>>>>> BEM VINDO(A) A LOJA DE ROUPAS <<<<<<\n")
    print("Selecione uma das opções do menu:\n")
    print("1- Inserir produto no estoque \n2- Encerrar Programa\n")
    opcao = int(input('Opção: '))

    while opcao >0:

      if opcao == 1:

        refazer = 1

        print("Informe o código do produto: ")
        codigo = input("CÓDIGO: ")

        print("Informe o nome do produto: ")
        nome = input("NOME: ")

        print("Informe o preço do produto: ")
        preco = float(input("PREÇO: "))

        print("Informe a quantidade: ")
        quantidade = int(input("QUANTIDADE: "))

        novositens = {codigo:[nome,preco,quantidade]} #DICIONÁRIO COM NOVOS ITENS
        estoque.update(novositens)  #ATUALIZAR DICIONÁRIO (ESTOQUE) COM DICIONÁRIO (NOVOS ITENS)
        print("\n\nProduto adicionado com sucesso!")

        while refazer == 1:
          print("\n\nSelecione uma opção.\n")
          print("0 - Voltar ao menu")
          print("1 - Inserir outro produto")
          refazer = int(input("Opção: "))
          
          if refazer <0 or refazer >1:
            print("\n\n****OPÇÃO INVÁLIDA****")
            refazer = 1
          elif refazer == 1:
            refazer = 0
            opcao = 2
          elif refazer == 0:
            opcao = 0

      elif opcao == 2:
        loop = 0
        opcao = 0
      
      else:
        print("****OPÇÃO INVÁLIDA****")
        opcao = 1

  #SE HOUVER ITENS NO ESTOQUE, MOSTRAR TODAS AS OPÇÕES DO MENU
  else:

    print("\n\n>>>>>> BEM VINDO(A) A LOJA DE ROUPAS <<<<<<\n")
    print("Selecione uma das opções do menu:\n")

    print("1- Listar Produtos no Estoque \n2- Inserir produto no estoque \n3- Remover produto do estoque \n4- Registrar item do cliente \n5- Encerrar Programa\n")
    opcao = int(input('Opção: '))

    while opcao >0:

      if opcao == 1:

        print("\nITENS EM ESTOQUE:\n")

        #LISTAR ITENS DO ESTOQUE
        for i in estoque:
          print(i,"-",estoque[i][0],"\nPreço: R$",estoque[i][1],"\nQuantidade:",estoque[i][2],"\n")

        opcao = 0

      #INSERIR PRODUTOS NO ESTOQUE
      elif opcao == 2:

        refazer = 1

        print("Informe o código do produto: \n")
        codigo = input("CÓDIGO: ")
        
        #SE JÁ HOUVER O CADASTRO DO PRODUTO, PERGUNTAR SE O USUÁRIO DESEJA ATUALIZAR
        if estoque.get(codigo) != None:
            
            update = 1
            
            print("O Código já existe no sistema...\n")
            print("ITEM:",estoque[codigo])
            
            while update >0:

              update = int(input("\n\nSelecione uma Opção:\n1- ATUALIZAR NOME \n2- ATUALIZAR PREÇO \n3- ATUALIZAR QUANTIDADE\n4- CANCELAR OPERAÇÃO\n\nOpção: "))
              
              if update == 1: #ATUALIZAR NOME DO PRODUTO
                nome = input("\nDigite o novo nome do produto: ")
                novoitem = {codigo:[nome,estoque[codigo][1],estoque[codigo][2]]}
                estoque.update(novoitem)
                print("Item",codigo,"atualizado para:",estoque[codigo])

              elif update == 2: #ATUALIZAR PREÇO DO PRODUTO
                preco = float(input("\nDigite o novo preço do produto: "))
                novoitem = {codigo:[estoque[codigo][0],preco,estoque[codigo][2]]}
                estoque.update(novoitem)
                print("Item",codigo,"atualizado para:",estoque[codigo])

              elif update == 3: #ATUALIZAR QUANTIDADE DO PRODUTO
                quantidade = int(input("\nDigite a nova quantidade do produto: "))
                novoitem = {codigo:[estoque[codigo][0],estoque[codigo][1],quantidade]}
                estoque.update(novoitem)
                print("Item",codigo,"atualizado para:",estoque[codigo])

              elif update == 4: #CANCELAR OPERAÇÃO
                print("OPERAÇÃO CANCELADA...")
                update = 0

              else:
                print("****OPÇÃO INVÁLIDA****")

            opcao = 0

        else: #CADASTRAR NOVO PRODUTO

            print("Informe o nome do produto: ")
            nome = input("NOME: ")
    
            print("Informe o preço do produto: ")
            preco = float(input("PREÇO: "))
    
            print("Informe a quantidade: ")
            quantidade = int(input("QUANTIDADE: "))
    
            novositens = {codigo:[nome,preco,quantidade]} #CRIAR UM DICIONÁRIO COM O NOVO PRODUTO
            estoque.update(novositens)  #ATUALIZAR DICIONÁRIO (ESTOQUE) COM O DICIONÁRIO QUE CONTÉM O NOVO PRODUTO
            print("\n\nProduto adicionado com sucesso!")
    
            while refazer == 1:
              print("\n\nSelecione uma opção.\n")
              print("0 - Voltar ao menu")
              print("1 - Inserir outro produto")
              refazer = int(input("Opção: "))
              
              if refazer <0 or refazer >1:
                print("\n\n****OPÇÃO INVÁLIDA****")
                refazer = 1
              elif refazer == 1:
                refazer = 0
                opcao = 2
              elif refazer == 0:
                opcao = 0

      #REMOVER PRODUTO DO ESTOQUE
      elif opcao == 3:

        refazer = 1
        
        print("Informe o Código do produto a ser removido.")
        codigo = input("\nCÓDIGO: ")

        #SE O PRODUTO EXISTIR
        if estoque.get(codigo) != None:
          del estoque[codigo] #REMOVER CODIGO DO PRODUTO
          print("\nProduto",codigo,"removido com sucesso! ")

          #MENU DE OPÇÕES
          while refazer ==1:
            print("\n\nSelecione uma opção.\n")
            print("0 - Voltar ao menu")
            print("1 - Remover outro Produto")
            print("2 - Listar itens em estoque")
            refazer = int(input("Opção: "))
            
            if refazer <0 or refazer >2:
              print("\n\n****OPÇÃO INVÁLIDA****")
              refazer = 1
            elif refazer == 1:
              refazer = 0
              opcao = 3
            elif refazer == 0:
              opcao = 0
            elif refazer == 2:
              print("\nItens em estoque: ")
              
              for i in estoque:
                print(i,"-",estoque[i][0])
              refazer = 1

        #SE O PRODUTO NÃO EXISTIR...
        else:
          print("\n\n****CÓDIGO INVÁLIDO****")

          while refazer ==1:
            print("\n\nSelecione uma opção.\n")
            print("0 - Voltar ao menu")
            print("1 - Remover outro Produto")
            print("2 - Listar itens em estoque")
            refazer = int(input("Opção: "))
            
            if refazer <0 or refazer >2:
              print("\n\n****OPÇÃO INVÁLIDA****")
              refazer = 1
            elif refazer == 1:
              refazer = 0
              opcao = 3
            elif refazer == 0:
              opcao = 0
            elif refazer == 2:
              print("\nItens em estoque: ")
              
              for i in estoque:
                print(i,"-",estoque[i][0])
              refazer = 1

      #REGISTRAR ITENS DO CLIENTE
      elif opcao == 4:

        listaClientes = {} #CRIAR DICIONÁRIO VAZIO
        maisum = 1

        print(">>>>>>>>>>> BEM VINDO AO BALCÃO DE CLIENTES <<<<<<<<<<<")
        print("Selecione uma das opções:\n")
        print("1- Comprar produtos (mínimo de 5 clientes)")
        print("2- Voltar ao MENU")

        comprar = int(input("\nOpção: "))
        
        if comprar == 1:

          clientes = 0

        elif comprar == 2:

          clientes = 5

        else:
          print("**** OPÇÃO INVÁLIDA ****")
          print("\nVoltando ao menu...")

        while clientes <5:
          
          nomeCliente = input("Nome do Cliente: ")

          print("\n>>>>>> ITENS DISPONÍVEIS <<<<<<")
          print("\n")

          for i in estoque: #LISTAR ITENS DO ESTOQUE
            print(i,"-",estoque[i][0],"\nPreço: R$",estoque[i][1],"\nQuantidade:",estoque[i][2],"\n")

          print("Olá",nomeCliente+"!")

          while maisum == 1: #LOOP PARA COMPRAR MAIS DE UM ITEM POR CLIENTE

            print("Digite o código do produto que deseja comprar.\n")
            codigo = input("CÓDIGO: ")

            if estoque.get(codigo) != None: #SE O CÓDIGO INFORMADO EXISTIR...

              quantidade = int(input("QUANTIDADE: ")) #INFORMAR QUANTIDADE QUE DESEJA COMPRAR

              if quantidade > estoque[codigo][2]: #SE A QUANTIDADE FOR MAIOR DO QUE EXISTE NO ESTOQUE...
                decisao = 0

                while decisao != 1 and decisao != 2:

                  print("NÃO HÁ ESTOQUE O SUFICIENTE PARA COMPRAR",estoque[codigo][0]) #MOSTRAR NOME DO PRODUTO
                  print("\nA quantidade em estoque é:",estoque[codigo][2]) #MOSTRAR QUANTIDADE EM ESTOQUE
                  
                  if estoque[codigo][2] > 0: #SE HOUVER PELO MENOS 1(UM) ITEM NO ESTOQUE

                    decisao = int(input("Deseja comprar a quantidade em estoque?\n1 = SIM\n2 = NÃO"))

                    if decisao == 1: #COMPRAR QUANTIDADE EM ESTOQUE
                      
                      quantidade = estoque[codigo][2]
                      preco = quantidade * estoque[codigo][1]
                      estoque[codigo][2] -= quantidade

                    elif decisao == 2: #NÃO COMPRAR QUANTIDADE EM ESTOQUE / CANCELAR OPERAÇÃO
                      codigo = None

                    else:
                      print("Opção inválida, tente novamente")

                  else:
                    decisao = 2
                    codigo = None

              else: #SE A QUANTIDADE FOR MENOR OU IGUAL A QUANTIDADE EM ESTOQUE

                preco = quantidade * estoque[codigo][1] #CALCULAR PREÇO TOTAL DO PRODUTO (PREÇO * QUANTIDADE)
                estoque[codigo][2] -= quantidade  #REMOVER A QUANTIDADE COMPRADA DO ESTOQUE

              if codigo != None: #SE O CÓDIGO EXISTIR...

                listatemp = [codigo,estoque[codigo][0],preco,quantidade] #CRIAR LISTA TEMPORÁRIA COM O PRODUTO, PREÇO TOTAL E A QUANTIDADE COMPRADA

                if listaClientes.get(nomeCliente) != None: #SE O CLIENTE JÁ EXISTIR NO DICIONÁRIO

                  listaClientes[nomeCliente].append(listatemp) #ADICIONAR LISTA TEMPORÁRIA NO DICIONÁRIO DO CLIENTE

                else: #SE O CLIENTE NÃO EXISTIR NO DICIONÁRIO...
                  listaClientes[nomeCliente] = [listatemp] #CRIAR DICIONÁRIO DO CLIENTE COM OS ITENS DA LISTA TEMPORÁRIA

                print("Item adicionado ao carrinho com sucesso!")

                print("\n\nInformações do seu Carrinho de compras:\n")
                print("Cliente:",nomeCliente)
                print("\nProdutos:\n")

                item = 0
                count = int(len(listaClientes[nomeCliente])) #CONTAR QUANTOS ITENS HÁ NO DICIONÁRIO DO CLIENTE
                count = int(count /4) #DIVIDIR O VALOR DA CONTAGEM POR 4, POIS CADA ITEM POSSUÍ 4 ITENS (CÓDIGO, PRODUTO, PREÇO, QUANTIDADE)
                print(listaClientes,"\n\n")
                while item < count: #LISTAR ITENS DO CARRINHO DE COMPRAS
                  print("Código:",listaClientes[nomeCliente][item],"Produto",listaClientes[nomeCliente][item+1],"Preço: R$",listaClientes[nomeCliente][item+2],"Quantidade:",listaClientes[nomeCliente][item+3],"\n")
                  item +=1

                maisum = 2

                while maisum != 1 and maisum != 0: #OPÇÃO PARA ADICIONAR MAIS UM ITEM NO CARRINHO

                  print("Deseja adicionar outro produto?")
                  print("1- SIM")
                  print("2- NÃO")
                  maisum = int(input("\n\nOpção: "))

                  if maisum == 2:
                    maisum = 0
                  elif maisum != 1:
                    print("OPÇÃO INVÁLIDA, TENTE NOVAMENTE...")
                  
              else:
                print("\nOPERAÇÃO CANCELADA...\n")

                maisum = 0

                while maisum != 1 and maisum != 2:

                  print("Deseja adicionar outro produto?")
                  print("1- SIM")
                  print("2- NÃO")
                  maisum = int(input("\nOpção: "))

                  if maisum == 2:
                    maisum = 0
                  elif maisum != 1:
                    print("OPÇÃO INVÁLIDA, TENTE NOVAMENTE...")


            else:
              print("CODIGO INVÁLIDO!")
              print("Selecione uma opção:")

              maisum = int(input("0 - Cancelar Operação\n1 - Inserir Outro Código"))
              
              while maisum != 0 and maisum != 1:

                print("OPÇÃO INVÁLIDA, TENTE NOVAMENTE")

                print("Selecione uma opção:")
                maisum = int(input("0 - Cancelar Operação\n1 - Inserir Outro Código"))

          if listaClientes.get(nomeCliente) != None:

            clientes +=1
            maisum = 1
          else:

            print("Cliente",nomeCliente,"foi removido do balcão por estar com o carrinho vázio...")
            maisum = 1
        
        for item in listaClientes: #ATENDIMENTO DE CAIXA ALEATÓRIO
          total = 0.0
          time.sleep(5) #AGUARDAR 5 SEGUNDOS
          x = random.randint(1,3) #GERAR UM NÚMERO ALEATÓRIO ENTRE 1 A 3 E ARMAZENAR NA VARIÁVEL
          print("\n>> Caixa Livre -",x,"<<")
          print("\n\nCliente:",item)
          print("_____________________________")
          for i in listaClientes[item]:
            print("\nCódigo:",i[0])
            print("Produto:",i[1])
            print("Quantidade:",i[3])
            print("Valor: R$",i[2])
            total = total + i[2]
          print("\nTotal a pagar: R$",total)
          print("_____________________________")
  

        listaClientes = {} #ZERAR CARRINHO DE COMPRAS E INFORMAÇÕES DO CLIENTE7

        opcao = 0


      #ENCERRAR PROGRAMA
      elif opcao == 5:
        loop = 0
        opcao = 0

      else:
        print("\n\n***OPÇÃO INVÁLIDA***")

print("\n\nPrograma encerrado.")